<?php
/**
 * @category   AvS
 * @package    AvS_Yoochoose
 * @author     Andreas von Studnitz <avs@avs-webentwicklung.de>
 */
?>

<?php $itemArray = $this->getItemArray() ?>
<?php if(count($itemArray)): ?>
<?php $i = 0 ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <table class="products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php for($row=0;$row<$this->getRowCount();$row++): ?>
        <tr>
        <?php for($column=0;$column<$this->getColumnCount();$column++): ?>
            <?php if(isset($itemArray[$i])): ?>
                <?php $_item=$itemArray[$i] ?>
                <?php $i++ ?>
            <td>
                <a href="<?php echo Mage::helper('yoochoose')->getProductUrl($_item) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo Mage::helper('yoochoose')->getProductUrl($_item) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true, '-upsell') ?>
                <?php echo $this->getReviewsSummaryHtml($_item) ?>
            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
