<?php
/**
 * @category    AvS
 * @package     AvS_Yoochoose
 * @author      Andreas von Studnitz <avs@avs-webentwicklung.de>
 */

/** @var $this AvS_Yoochoose_Block_Tracking */
?>

<?php 
if (Mage::helper('yoochoose')->isActive() && sizeof($this->getTrackingPixelData()) > 0): 
?>

<div id="yoochoose_tracking">
	<?php foreach ($this->getTrackingPixelData() as $trackingPixelData): ?>
		<img src="<?php echo $this->generateTrackingPixelUrl($trackingPixelData) ?>" alt="<?php echo $this->__('Yoochoose Tracking') ?>" width="0" height="0" />
	<?php endforeach ?>
</div>

<?php endif ?>

