<?php    
    $_productCollection=$this->getItemArray();   
    $_helper = $this->helper('catalog/output');
    $_columnCount = $this->getColumnCount();
	
	$conf = new Gala_Galaeverbuysettings_Galaeverbuysettings();
	$w = $conf->get_grid_thumb_width();
	$h = $conf->get_grid_thumb_height();
   
?>
<?php if(!count($_productCollection)): ?>
<!-- yoochoose: no products found for [<?php echo $this->getBlockName(); ?>] -->
<?php else: ?>
	<div class="featured_products">
	<h3><?php echo $this->getBlockName(); ?></h3>
    <div class="category-products">   
    <?php $i=0; foreach ($_productCollection as $_product): ?>  
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h); ?>" width="<?php echo $w ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<?php Mage::helper('productlabels')->display($_product); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                		
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>               
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>                   
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_productCollection)): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	</div>
	</div>
<?php endif; ?>